### ISSUE TITLE
Does this only support the `vita` fork of openPifPaf?

### ISSUE THREAD

**Issue by njho** [openpifpaf/openpifpaf_posetrack#10]
The link in the readme leads to the following location: 

https://github.com/vita-epfl/openpifpaf

**Comment by njho** [comment]
In order to have this repo work you must install `openPifPaf` w/ 

`pip install openpifpaf==0.12.5` or `pip install openpifpaf==0.12.4` as seen at: https://pypi.org/project/openpifpaf/#history

It works only with `--checkpoint tshufflenetv2k16` and `detector:0` and `detector:1` combinations

per command: 
MPLBACKEND=macosx python3 -m openpifpaf.video --show --long-edge=321 --checkpoint=tshufflenetv2k16 --decoder=trackingpose:0 --source 0 --horizontal-flip


`tshufflnetv2k30` is not supported

**Comment by svenkreiss** [comment]
I agree, this might be the only way to get the pretrained `tshufflenetv2k16` to run now. However, the updated model is the `tshufflenetv2k30` that works with the latest of OpenPifPaf 0.13.3.

For that, uninstall this plugin. Only install `openpifpaf`. And run your above command with the 30 model instead of the 16.
